---
- name: create app directory
  file:
    path: "{{ api_home }}"
    state: "directory"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
  become: true

- name: create secrets directory
  file:
    path: "{{ user_home }}/.google"
    state: "directory"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: install google api key
  template:
    src: "njsquared.json.j2"
    dest: "{{ user_home }}/.google/njsquared.json"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0644

- name: install api
  command: "cp -R {{ user_home }}/njsquared/app {{ api_home }}"

- name: set file permissions
  file:
    path: "{{ api_home }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755
    recurse: yes

- name: install systemd script
  template:
    src: "njsquared.service.j2"
    dest: "/etc/systemd/system/njsquared.service"
    owner: root
    group: root
    mode: 0664
  become: true
  become_user: root

- name: enable systemd script
  command: "systemctl enable njsquared.service"
  become: true
  become_user: root

- name: run service
  command: "systemctl start njsquared.service"
  become: true
  become_user: root
